pipeline {
  agent any

  tools {
    jfrog 'jfrog-cli'
  }

  environment {
    IMAGE_NAME = "tompazus.jfrog.io/docker-virtual/plusone-app"
    GIT_COMMIT = "${env.GIT_COMMIT}"
    BUILD_NAME = "plusone-app"
    BUILD_NUMBER = "${BUILD_NUMBER}"
  }

  stages {
    stage('Configure JFrog CLI') {
      steps {
        withCredentials([string(credentialsId: 'jfrog-access-token', variable: 'ACCESS_TOKEN')]) {
          sh '''
            jf c add jfrog-server \
              --url=https://tompazus.jfrog.io \
              --access-token=$ACCESS_TOKEN \
              --interactive=false \
              --overwrite=true \
              --artifactory-url=https://tompazus.jfrog.io/artifactory \
              --xray-url=https://tompazus.jfrog.io/xray

            jf rt bce plusone-app $BUILD_NUMBER
          '''
        }
      }
    }

    stage('Build and scan image') {
      steps {
        script {
          def dockerImageName = "${IMAGE_NAME}:${BUILD_NUMBER}"
          sh """
            if docker buildx ls | grep -q 'mybuilder'; then
              docker buildx use mybuilder
            else
              docker buildx create --use --name mybuilder
            fi
            cd plusone
            jf docker build -t ${dockerImageName} . --build-name=${BUILD_NAME} --build-number=${BUILD_NUMBER}
          """
          sh """
            export JFROG_CLI_BUILD_NAME=${BUILD_NAME}
            export JFROG_CLI_BUILD_NUMBER=${BUILD_NUMBER}
            jf docker scan ${dockerImageName} --build-name=${BUILD_NAME} --build-number=${BUILD_NUMBER}
          """
        }
      }
    }

    stage('Push multi-platform image') {
      steps {
        script {
          def dockerImageName = "${IMAGE_NAME}:${BUILD_NUMBER}"
          sh """
            cd plusone
            jf docker push ${dockerImageName} --build-name=${BUILD_NAME} --build-number=${BUILD_NUMBER}
          """
        }
      }
    }

    stage('Publish build info') {
      steps {
        sh """
          jf rt build-add-git ${BUILD_NAME} ${BUILD_NUMBER} # connect to git metadata and repo
          jf rt build-collect-env ${BUILD_NAME} ${BUILD_NUMBER} # show ENV variables
          jf rt build-publish ${BUILD_NAME} ${BUILD_NUMBER} # push info to rt 
        """
      }
    }

    stage('Kubernetes Deployment - DEV') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'helm-keys', usernameVariable: 'ARTIFACTORY_USERNAME', passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
            sh """
              export KUBECONFIG=/var/lib/jenkins/.kube/config
              kubectl get pods
  
              # Authenticate with Artifactory
              helm pull oci://tompazus.jfrog.io/se-helm-local/plusone-chart --version 1.0.0 --username $ARTIFACTORY_USERNAME --password $ARTIFACTORY_PASSWORD

              CHART_FILE=\$(ls plusone-chart-*.tgz)
  
              # Install or upgrade from Artifactory
              helm upgrade --install plusone-chart \$CHART_FILE --set image.tag=${BUILD_NUMBER} --wait --timeout 5m --atomic
            """
          }
        }
      }
    }
  }
}
