pipeline {
    agent any

    parameters {
        choice(name: 'CHART_NAME', choices: ['numeric', 'plusone'], description: 'Select the chart name')
        string(name: 'CHART_VERSION', defaultValue: '1.0.0', description: 'Enter the chart version')
    }

    environment {
        ARTIFACTORY_REPO = "tompazus.jfrog.io/se-helm-local"
        FINAL_CHART_NAME = "${params.CHART_NAME}-chart"
    }

    stages {
        stage('Declarative: Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Login to Artifactory with Access Token') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'helm-keys', usernameVariable: 'ARTIFACTORY_USERNAME', passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                        sh """
                        helm registry login $ARTIFACTORY_REPO --username $ARTIFACTORY_USERNAME --password $ARTIFACTORY_PASSWORD
                        """
                    }
                }
            }
        }

        stage('Package Helm Chart') {
            steps {
                sh """
                helm package charts/${FINAL_CHART_NAME} --version ${params.CHART_VERSION}
                """
            }
        }

        stage('Push Helm Chart to OCI') {
            steps {
                sh """
                helm push ${FINAL_CHART_NAME}-${params.CHART_VERSION}.tgz oci://$ARTIFACTORY_REPO
                """
            }
        }
    }

    post {
        success {
            echo '✅ Helm chart pushed successfully!'
        }
        failure {
            echo '❌ Pipeline failed. Check logs for errors.'
        }
    }
}
